//! Sail language keywords + built-in identifiers.
//!
//! Stage — extracted from `sail_server::backend` so the
//! completion engine in `crates/ide` can offer keyword / builtin
//! completions without depending on sail_server.

pub const SAIL_KEYWORDS: &[&str] = &[
    "and",
    "as",
    "assert",
    "backwards",
    "bitfield",
    "by",
    "catch",
    "clause",
    "configuration",
    "constant",
    "constraint",
    "dec",
    "default",
    "do",
    "downto",
    "effect",
    "else",
    "end",
    "enum",
    "exit",
    "forall",
    "foreach",
    "forwards",
    "from",
    "function",
    "if",
    "impl",
    "in",
    "inc",
    "infix",
    "infixl",
    "infixr",
    "instantiation",
    "let",
    "mapping",
    "match",
    "mutual",
    "newtype",
    "outcome",
    "overload",
    "private",
    "pure",
    "ref",
    "register",
    "repeat",
    "return",
    "scattered",
    "sizeof",
    "struct",
    "termination_measure",
    "then",
    "throw",
    "to",
    "try",
    "type",
    "union",
    "until",
    "val",
    "var",
    "when",
    "while",
    "with",
];

pub const SAIL_BUILTINS: &[&str] = &[
    // Kind names
    "Int",
    "Nat",
    "Type",
    "Order",
    "Bool",
    // Literal values
    "true",
    "false",
    "undefined",
    "bitzero",
    "bitone",
    // Common types
    "int",
    "nat",
    "bool",
    "unit",
    "bit",
    "real",
    "string",
    "bits",
    "vector",
    "list",
    "option",
    "range",
    "atom",
    "implicit",
    // Option/Result constructors
    "None",
    "Some",
    // Common prelude functions (from sail/lib/prelude.sail)
    "sail_zeros",
    "sail_ones",
    "sail_sign_extend",
    "sail_zero_extend",
    "length",
    "bitvector_length",
    "unsigned",
    "signed",
    "not_bool",
    "and_bool",
    "or_bool",
    "eq_int",
    "eq_bool",
    "eq_string",
    "eq_bit",
    "add_int",
    "sub_int",
    "mult_int",
    "negate_int",
    "add_atom",
    "sub_atom",
    "string_append",
    "string_length",
    "string_of_int",
    "print",
    "print_int",
    "print_string",
    "print_endline",
    "assert",
    "exit",
    "throw",
    "read_reg",
    "write_reg",
    // Vector operations
    "vector_access",
    "vector_subrange",
    "vector_update",
    "vector_update_subrange",
    "vector_concat",
    "append",
    "replicate_bits",
    // Bitwise operations
    "not_vec",
    "and_vec",
    "or_vec",
    "xor_vec",
    // Arithmetic
    "pow2",
    "tdiv_int",
    "tmod_int",
    // Sail special
    "__FILE__",
    "__LINE__",
];

/// Check if a name is a Sail keyword.
pub fn is_keyword(name: &str) -> bool {
    SAIL_KEYWORDS.contains(&name)
}
