//! Rowan language integration for Sail.
//! Defines `SailLanguage` (the rowan `Language` impl), `SyntaxNode`,
//! `SyntaxToken`, and `SyntaxElement`. This is the single source of
//! truth for these types — matching RA where `RustLanguage` lives in
//! the syntax crate, not the parser crate.

use parser::SyntaxKind;

use crate::syntax_error::SyntaxError;
use crate::Parse;

pub(crate) use rowan::GreenNode;

/// Rowan language tag for Sail.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SailLanguage {}

impl rowan::Language for SailLanguage {
    type Kind = SyntaxKind;

    // generated by the SyntaxKind derive proc-macro. We use an unsafe transmute
    // guarded by a bounds assert instead — functionally equivalent.
    // TODO: generate `impl From<u16> for SyntaxKind` in parser's codegen to
    // eliminate the transmute and match RA exactly.
    fn kind_from_raw(raw: rowan::SyntaxKind) -> SyntaxKind {
        assert!((raw.0 as usize) < SyntaxKind::__LAST as usize);
        // SAFETY: SyntaxKind is repr(u16) and raw.0 is in range.
        unsafe { std::mem::transmute::<u16, SyntaxKind>(raw.0) }
    }

    fn kind_to_raw(kind: SyntaxKind) -> rowan::SyntaxKind {
        rowan::SyntaxKind(kind as u16)
    }
}

pub type SyntaxNode = rowan::SyntaxNode<SailLanguage>;
pub type SyntaxToken = rowan::SyntaxToken<SailLanguage>;
pub type SyntaxElement = rowan::SyntaxElement<SailLanguage>;
pub type SyntaxNodeChildren = rowan::SyntaxNodeChildren<SailLanguage>;
pub type SyntaxElementChildren = rowan::SyntaxElementChildren<SailLanguage>;
pub type PreorderWithTokens = rowan::api::PreorderWithTokens<SailLanguage>;

/// Helper for building a rowan `GreenNode` + collecting errors.
pub struct SyntaxTreeBuilder {
    errors: Vec<SyntaxError>,
    inner: rowan::GreenNodeBuilder<'static>,
}

impl Default for SyntaxTreeBuilder {
    fn default() -> Self {
        Self { errors: Vec::new(), inner: rowan::GreenNodeBuilder::new() }
    }
}

impl SyntaxTreeBuilder {
    /// Consume the builder, returning raw `(GreenNode, errors)`.
    ///
    /// TODO: RA marks this `pub(crate)`; we expose it as `pub` for use by
    /// `parser_lower`. Restrict once the parser_lower boundary is settled.
    pub fn finish_raw(self) -> (GreenNode, Vec<SyntaxError>) {
        let green = self.inner.finish();
        (green, self.errors)
    }

    /// Consume the builder, returning a `Parse<SyntaxNode>`.
    pub fn finish(self) -> Parse<SyntaxNode> {
        let (green, errors) = self.finish_raw();
        // Validate that the root is a SyntaxNode (it always is)
        let _root = SyntaxNode::new_root(green.clone());
        Parse::new(green, errors)
    }

    /// Emit a token.
    pub fn token(&mut self, kind: SyntaxKind, text: &str) {
        let raw = rowan::SyntaxKind(kind as u16);
        self.inner.token(raw, text);
    }

    /// Start a composite node.
    pub fn start_node(&mut self, kind: SyntaxKind) {
        let raw = rowan::SyntaxKind(kind as u16);
        self.inner.start_node(raw);
    }

    /// Finish the most recently started node.
    pub fn finish_node(&mut self) {
        self.inner.finish_node();
    }

    /// Record an error at the given text position.
    pub fn error(&mut self, error: String, text_pos: rowan::TextSize) {
        self.errors.push(SyntaxError::new_at_offset(error, text_pos));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_simple_tree() {
        let mut b = SyntaxTreeBuilder::default();
        b.start_node(SyntaxKind::SOURCE_FILE);
        b.token(SyntaxKind::KW_VAL, "val");
        b.token(SyntaxKind::WHITESPACE, " ");
        b.token(SyntaxKind::IDENT, "x");
        b.finish_node();

        let (green, errors) = b.finish_raw();
        assert!(errors.is_empty());
        let root = SyntaxNode::new_root(green);
        assert_eq!(root.kind(), SyntaxKind::SOURCE_FILE);
        assert_eq!(root.text().to_string(), "val x");
    }

    #[test]
    fn build_tree_with_error() {
        let mut b = SyntaxTreeBuilder::default();
        b.start_node(SyntaxKind::SOURCE_FILE);
        b.token(SyntaxKind::KW_VAL, "val");
        b.error("expected identifier".to_string(), rowan::TextSize::from(3));
        b.finish_node();

        let (green, errors) = b.finish_raw();
        assert_eq!(errors.len(), 1);
        assert_eq!(errors[0].message(), "expected identifier");
        let root = SyntaxNode::new_root(green);
        assert_eq!(root.text().to_string(), "val");
    }

    #[test]
    fn finish_returns_parse() {
        let mut b = SyntaxTreeBuilder::default();
        b.start_node(SyntaxKind::SOURCE_FILE);
        b.token(SyntaxKind::IDENT, "x");
        b.finish_node();

        let parse = b.finish();
        assert!(parse.errors().is_empty());
        assert_eq!(parse.syntax_node().kind(), SyntaxKind::SOURCE_FILE);
    }
}
